//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  global_settings: Global_Settings;
  global_settingsConnection: Global_SettingsConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  about_page: About_Page;
  about_pageConnection: About_PageConnection;
  testimonials_page: Testimonials_Page;
  testimonials_pageConnection: Testimonials_PageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobal_SettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobal_SettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Global_SettingsFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryAbout_PageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAbout_PageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<About_PageFilter>;
};


export type QueryTestimonials_PageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonials_PageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Testimonials_PageFilter>;
};

export type DocumentFilter = {
  global_settings?: InputMaybe<Global_SettingsFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  service?: InputMaybe<ServiceFilter>;
  about_page?: InputMaybe<About_PageFilter>;
  testimonials_page?: InputMaybe<Testimonials_PageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Global_Settings | Homepage | Service | About_Page | Testimonials_Page | Folder;

export type Global_SettingsNavigation_Links = {
  __typename?: 'Global_settingsNavigation_links';
  label?: Maybe<Scalars['String']['output']>;
  path?: Maybe<Scalars['String']['output']>;
};

export type Global_SettingsSocial_Links = {
  __typename?: 'Global_settingsSocial_links';
  platform?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Global_Settings = Node & Document & {
  __typename?: 'Global_settings';
  logo?: Maybe<Scalars['String']['output']>;
  primary_phone?: Maybe<Scalars['String']['output']>;
  secondary_phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  navigation_links?: Maybe<Array<Maybe<Global_SettingsNavigation_Links>>>;
  social_links?: Maybe<Array<Maybe<Global_SettingsSocial_Links>>>;
  footer_services?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  services_page_title?: Maybe<Scalars['String']['output']>;
  footer_text?: Maybe<Scalars['String']['output']>;
  footer_credit?: Maybe<Scalars['String']['output']>;
  cta_button_label?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Global_SettingsNavigation_LinksFilter = {
  label?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
};

export type Global_SettingsSocial_LinksFilter = {
  platform?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Global_SettingsFilter = {
  logo?: InputMaybe<ImageFilter>;
  primary_phone?: InputMaybe<StringFilter>;
  secondary_phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  navigation_links?: InputMaybe<Global_SettingsNavigation_LinksFilter>;
  social_links?: InputMaybe<Global_SettingsSocial_LinksFilter>;
  footer_services?: InputMaybe<StringFilter>;
  services_page_title?: InputMaybe<StringFilter>;
  footer_text?: InputMaybe<StringFilter>;
  footer_credit?: InputMaybe<StringFilter>;
  cta_button_label?: InputMaybe<StringFilter>;
};

export type Global_SettingsConnectionEdges = {
  __typename?: 'Global_settingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global_Settings>;
};

export type Global_SettingsConnection = Connection & {
  __typename?: 'Global_settingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Global_SettingsConnectionEdges>>>;
};

export type HomepageFeatures = {
  __typename?: 'HomepageFeatures';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  icon_key?: Maybe<Scalars['String']['output']>;
  border_color?: Maybe<Scalars['String']['output']>;
};

export type HomepageReviews = {
  __typename?: 'HomepageReviews';
  avatar?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['Float']['output']>;
  text?: Maybe<Scalars['JSON']['output']>;
  platform?: Maybe<Scalars['String']['output']>;
};

export type HomepageFaqs = {
  __typename?: 'HomepageFaqs';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['JSON']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  hero_line_one?: Maybe<Scalars['String']['output']>;
  hero_line_one_suffix?: Maybe<Scalars['String']['output']>;
  hero_line_two?: Maybe<Scalars['String']['output']>;
  hero_line_three?: Maybe<Scalars['String']['output']>;
  hero_image_1?: Maybe<Scalars['String']['output']>;
  hero_image_2?: Maybe<Scalars['String']['output']>;
  hero_image_3?: Maybe<Scalars['String']['output']>;
  hero_arrow?: Maybe<Scalars['String']['output']>;
  hero_button_label?: Maybe<Scalars['String']['output']>;
  hero_phone_label?: Maybe<Scalars['String']['output']>;
  about_title?: Maybe<Scalars['String']['output']>;
  about_text?: Maybe<Scalars['JSON']['output']>;
  about_image?: Maybe<Scalars['String']['output']>;
  features_title?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<HomepageFeatures>>>;
  services_title?: Maybe<Scalars['String']['output']>;
  reviews_title?: Maybe<Scalars['String']['output']>;
  reviews?: Maybe<Array<Maybe<HomepageReviews>>>;
  faq_title?: Maybe<Scalars['String']['output']>;
  faqs?: Maybe<Array<Maybe<HomepageFaqs>>>;
  cta_title?: Maybe<Scalars['String']['output']>;
  cta_description?: Maybe<Scalars['String']['output']>;
  cta_button_label?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomepageFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  icon_key?: InputMaybe<StringFilter>;
  border_color?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type HomepageReviewsFilter = {
  avatar?: InputMaybe<ImageFilter>;
  name?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
  text?: InputMaybe<RichTextFilter>;
  platform?: InputMaybe<StringFilter>;
};

export type HomepageFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<RichTextFilter>;
};

export type HomepageFilter = {
  hero_line_one?: InputMaybe<StringFilter>;
  hero_line_one_suffix?: InputMaybe<StringFilter>;
  hero_line_two?: InputMaybe<StringFilter>;
  hero_line_three?: InputMaybe<StringFilter>;
  hero_image_1?: InputMaybe<ImageFilter>;
  hero_image_2?: InputMaybe<ImageFilter>;
  hero_image_3?: InputMaybe<ImageFilter>;
  hero_arrow?: InputMaybe<ImageFilter>;
  hero_button_label?: InputMaybe<StringFilter>;
  hero_phone_label?: InputMaybe<StringFilter>;
  about_title?: InputMaybe<StringFilter>;
  about_text?: InputMaybe<RichTextFilter>;
  about_image?: InputMaybe<ImageFilter>;
  features_title?: InputMaybe<StringFilter>;
  features?: InputMaybe<HomepageFeaturesFilter>;
  services_title?: InputMaybe<StringFilter>;
  reviews_title?: InputMaybe<StringFilter>;
  reviews?: InputMaybe<HomepageReviewsFilter>;
  faq_title?: InputMaybe<StringFilter>;
  faqs?: InputMaybe<HomepageFaqsFilter>;
  cta_title?: InputMaybe<StringFilter>;
  cta_description?: InputMaybe<StringFilter>;
  cta_button_label?: InputMaybe<StringFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  cta_label?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiceFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  cta_label?: InputMaybe<StringFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type About_Page = Node & Document & {
  __typename?: 'About_page';
  hero_title_prefix?: Maybe<Scalars['String']['output']>;
  hero_title_brand?: Maybe<Scalars['String']['output']>;
  hero_title_suffix?: Maybe<Scalars['String']['output']>;
  hero_button_label?: Maybe<Scalars['String']['output']>;
  about_title?: Maybe<Scalars['String']['output']>;
  about_text?: Maybe<Scalars['JSON']['output']>;
  about_image?: Maybe<Scalars['String']['output']>;
  vision_title?: Maybe<Scalars['String']['output']>;
  vision_text?: Maybe<Scalars['String']['output']>;
  vision_image?: Maybe<Scalars['String']['output']>;
  mission_title?: Maybe<Scalars['String']['output']>;
  mission_text?: Maybe<Scalars['String']['output']>;
  mission_image?: Maybe<Scalars['String']['output']>;
  cabinet_title?: Maybe<Scalars['String']['output']>;
  cabinet_images?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  send_message_title?: Maybe<Scalars['String']['output']>;
  cta_title?: Maybe<Scalars['String']['output']>;
  cta_description?: Maybe<Scalars['String']['output']>;
  cta_button_label?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type About_PageFilter = {
  hero_title_prefix?: InputMaybe<StringFilter>;
  hero_title_brand?: InputMaybe<StringFilter>;
  hero_title_suffix?: InputMaybe<StringFilter>;
  hero_button_label?: InputMaybe<StringFilter>;
  about_title?: InputMaybe<StringFilter>;
  about_text?: InputMaybe<RichTextFilter>;
  about_image?: InputMaybe<ImageFilter>;
  vision_title?: InputMaybe<StringFilter>;
  vision_text?: InputMaybe<StringFilter>;
  vision_image?: InputMaybe<ImageFilter>;
  mission_title?: InputMaybe<StringFilter>;
  mission_text?: InputMaybe<StringFilter>;
  mission_image?: InputMaybe<ImageFilter>;
  cabinet_title?: InputMaybe<StringFilter>;
  cabinet_images?: InputMaybe<ImageFilter>;
  send_message_title?: InputMaybe<StringFilter>;
  cta_title?: InputMaybe<StringFilter>;
  cta_description?: InputMaybe<StringFilter>;
  cta_button_label?: InputMaybe<StringFilter>;
};

export type About_PageConnectionEdges = {
  __typename?: 'About_pageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About_Page>;
};

export type About_PageConnection = Connection & {
  __typename?: 'About_pageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<About_PageConnectionEdges>>>;
};

export type Testimonials_PageBefore_After_Pairs = {
  __typename?: 'Testimonials_pageBefore_after_pairs';
  before_image?: Maybe<Scalars['String']['output']>;
  after_image?: Maybe<Scalars['String']['output']>;
  before_alt?: Maybe<Scalars['String']['output']>;
  after_alt?: Maybe<Scalars['String']['output']>;
};

export type Testimonials_PageMore_Panels = {
  __typename?: 'Testimonials_pageMore_panels';
  kind?: Maybe<Scalars['String']['output']>;
  src?: Maybe<Scalars['String']['output']>;
  poster?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Testimonials_Page = Node & Document & {
  __typename?: 'Testimonials_page';
  hero_title_line_one?: Maybe<Scalars['String']['output']>;
  hero_title_highlight?: Maybe<Scalars['String']['output']>;
  hero_title_line_two?: Maybe<Scalars['String']['output']>;
  hero_title_line_three?: Maybe<Scalars['String']['output']>;
  hero_description?: Maybe<Scalars['String']['output']>;
  hero_button_label?: Maybe<Scalars['String']['output']>;
  hero_image_1?: Maybe<Scalars['String']['output']>;
  hero_image_2?: Maybe<Scalars['String']['output']>;
  hero_image_3?: Maybe<Scalars['String']['output']>;
  before_after_title?: Maybe<Scalars['String']['output']>;
  before_after_pairs?: Maybe<Array<Maybe<Testimonials_PageBefore_After_Pairs>>>;
  more_title?: Maybe<Scalars['String']['output']>;
  more_panels?: Maybe<Array<Maybe<Testimonials_PageMore_Panels>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Testimonials_PageBefore_After_PairsFilter = {
  before_image?: InputMaybe<ImageFilter>;
  after_image?: InputMaybe<ImageFilter>;
  before_alt?: InputMaybe<StringFilter>;
  after_alt?: InputMaybe<StringFilter>;
};

export type Testimonials_PageMore_PanelsFilter = {
  kind?: InputMaybe<StringFilter>;
  src?: InputMaybe<StringFilter>;
  poster?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Testimonials_PageFilter = {
  hero_title_line_one?: InputMaybe<StringFilter>;
  hero_title_highlight?: InputMaybe<StringFilter>;
  hero_title_line_two?: InputMaybe<StringFilter>;
  hero_title_line_three?: InputMaybe<StringFilter>;
  hero_description?: InputMaybe<StringFilter>;
  hero_button_label?: InputMaybe<StringFilter>;
  hero_image_1?: InputMaybe<ImageFilter>;
  hero_image_2?: InputMaybe<ImageFilter>;
  hero_image_3?: InputMaybe<ImageFilter>;
  before_after_title?: InputMaybe<StringFilter>;
  before_after_pairs?: InputMaybe<Testimonials_PageBefore_After_PairsFilter>;
  more_title?: InputMaybe<StringFilter>;
  more_panels?: InputMaybe<Testimonials_PageMore_PanelsFilter>;
};

export type Testimonials_PageConnectionEdges = {
  __typename?: 'Testimonials_pageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonials_Page>;
};

export type Testimonials_PageConnection = Connection & {
  __typename?: 'Testimonials_pageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Testimonials_PageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateGlobal_settings: Global_Settings;
  createGlobal_settings: Global_Settings;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateService: Service;
  createService: Service;
  updateAbout_page: About_Page;
  createAbout_page: About_Page;
  updateTestimonials_page: Testimonials_Page;
  createTestimonials_page: Testimonials_Page;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateGlobal_SettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: Global_SettingsMutation;
};


export type MutationCreateGlobal_SettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: Global_SettingsMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateAbout_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: About_PageMutation;
};


export type MutationCreateAbout_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: About_PageMutation;
};


export type MutationUpdateTestimonials_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: Testimonials_PageMutation;
};


export type MutationCreateTestimonials_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: Testimonials_PageMutation;
};

export type DocumentUpdateMutation = {
  global_settings?: InputMaybe<Global_SettingsMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  service?: InputMaybe<ServiceMutation>;
  about_page?: InputMaybe<About_PageMutation>;
  testimonials_page?: InputMaybe<Testimonials_PageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  global_settings?: InputMaybe<Global_SettingsMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  service?: InputMaybe<ServiceMutation>;
  about_page?: InputMaybe<About_PageMutation>;
  testimonials_page?: InputMaybe<Testimonials_PageMutation>;
};

export type Global_SettingsNavigation_LinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
};

export type Global_SettingsSocial_LinksMutation = {
  platform?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type Global_SettingsMutation = {
  logo?: InputMaybe<Scalars['String']['input']>;
  primary_phone?: InputMaybe<Scalars['String']['input']>;
  secondary_phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  navigation_links?: InputMaybe<Array<InputMaybe<Global_SettingsNavigation_LinksMutation>>>;
  social_links?: InputMaybe<Array<InputMaybe<Global_SettingsSocial_LinksMutation>>>;
  footer_services?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  services_page_title?: InputMaybe<Scalars['String']['input']>;
  footer_text?: InputMaybe<Scalars['String']['input']>;
  footer_credit?: InputMaybe<Scalars['String']['input']>;
  cta_button_label?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  icon_key?: InputMaybe<Scalars['String']['input']>;
  border_color?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageReviewsMutation = {
  avatar?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
  text?: InputMaybe<Scalars['JSON']['input']>;
  platform?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomepageMutation = {
  hero_line_one?: InputMaybe<Scalars['String']['input']>;
  hero_line_one_suffix?: InputMaybe<Scalars['String']['input']>;
  hero_line_two?: InputMaybe<Scalars['String']['input']>;
  hero_line_three?: InputMaybe<Scalars['String']['input']>;
  hero_image_1?: InputMaybe<Scalars['String']['input']>;
  hero_image_2?: InputMaybe<Scalars['String']['input']>;
  hero_image_3?: InputMaybe<Scalars['String']['input']>;
  hero_arrow?: InputMaybe<Scalars['String']['input']>;
  hero_button_label?: InputMaybe<Scalars['String']['input']>;
  hero_phone_label?: InputMaybe<Scalars['String']['input']>;
  about_title?: InputMaybe<Scalars['String']['input']>;
  about_text?: InputMaybe<Scalars['JSON']['input']>;
  about_image?: InputMaybe<Scalars['String']['input']>;
  features_title?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<HomepageFeaturesMutation>>>;
  services_title?: InputMaybe<Scalars['String']['input']>;
  reviews_title?: InputMaybe<Scalars['String']['input']>;
  reviews?: InputMaybe<Array<InputMaybe<HomepageReviewsMutation>>>;
  faq_title?: InputMaybe<Scalars['String']['input']>;
  faqs?: InputMaybe<Array<InputMaybe<HomepageFaqsMutation>>>;
  cta_title?: InputMaybe<Scalars['String']['input']>;
  cta_description?: InputMaybe<Scalars['String']['input']>;
  cta_button_label?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  cta_label?: InputMaybe<Scalars['String']['input']>;
};

export type About_PageMutation = {
  hero_title_prefix?: InputMaybe<Scalars['String']['input']>;
  hero_title_brand?: InputMaybe<Scalars['String']['input']>;
  hero_title_suffix?: InputMaybe<Scalars['String']['input']>;
  hero_button_label?: InputMaybe<Scalars['String']['input']>;
  about_title?: InputMaybe<Scalars['String']['input']>;
  about_text?: InputMaybe<Scalars['JSON']['input']>;
  about_image?: InputMaybe<Scalars['String']['input']>;
  vision_title?: InputMaybe<Scalars['String']['input']>;
  vision_text?: InputMaybe<Scalars['String']['input']>;
  vision_image?: InputMaybe<Scalars['String']['input']>;
  mission_title?: InputMaybe<Scalars['String']['input']>;
  mission_text?: InputMaybe<Scalars['String']['input']>;
  mission_image?: InputMaybe<Scalars['String']['input']>;
  cabinet_title?: InputMaybe<Scalars['String']['input']>;
  cabinet_images?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  send_message_title?: InputMaybe<Scalars['String']['input']>;
  cta_title?: InputMaybe<Scalars['String']['input']>;
  cta_description?: InputMaybe<Scalars['String']['input']>;
  cta_button_label?: InputMaybe<Scalars['String']['input']>;
};

export type Testimonials_PageBefore_After_PairsMutation = {
  before_image?: InputMaybe<Scalars['String']['input']>;
  after_image?: InputMaybe<Scalars['String']['input']>;
  before_alt?: InputMaybe<Scalars['String']['input']>;
  after_alt?: InputMaybe<Scalars['String']['input']>;
};

export type Testimonials_PageMore_PanelsMutation = {
  kind?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
  poster?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type Testimonials_PageMutation = {
  hero_title_line_one?: InputMaybe<Scalars['String']['input']>;
  hero_title_highlight?: InputMaybe<Scalars['String']['input']>;
  hero_title_line_two?: InputMaybe<Scalars['String']['input']>;
  hero_title_line_three?: InputMaybe<Scalars['String']['input']>;
  hero_description?: InputMaybe<Scalars['String']['input']>;
  hero_button_label?: InputMaybe<Scalars['String']['input']>;
  hero_image_1?: InputMaybe<Scalars['String']['input']>;
  hero_image_2?: InputMaybe<Scalars['String']['input']>;
  hero_image_3?: InputMaybe<Scalars['String']['input']>;
  before_after_title?: InputMaybe<Scalars['String']['input']>;
  before_after_pairs?: InputMaybe<Array<InputMaybe<Testimonials_PageBefore_After_PairsMutation>>>;
  more_title?: InputMaybe<Scalars['String']['input']>;
  more_panels?: InputMaybe<Array<InputMaybe<Testimonials_PageMore_PanelsMutation>>>;
};

export type Global_SettingsPartsFragment = { __typename: 'Global_settings', logo?: string | null, primary_phone?: string | null, secondary_phone?: string | null, email?: string | null, address?: string | null, footer_services?: Array<string | null> | null, services_page_title?: string | null, footer_text?: string | null, footer_credit?: string | null, cta_button_label?: string | null, navigation_links?: Array<{ __typename: 'Global_settingsNavigation_links', label?: string | null, path?: string | null } | null> | null, social_links?: Array<{ __typename: 'Global_settingsSocial_links', platform?: string | null, url?: string | null } | null> | null };

export type HomepagePartsFragment = { __typename: 'Homepage', hero_line_one?: string | null, hero_line_one_suffix?: string | null, hero_line_two?: string | null, hero_line_three?: string | null, hero_image_1?: string | null, hero_image_2?: string | null, hero_image_3?: string | null, hero_arrow?: string | null, hero_button_label?: string | null, hero_phone_label?: string | null, about_title?: string | null, about_text?: any | null, about_image?: string | null, features_title?: string | null, services_title?: string | null, reviews_title?: string | null, faq_title?: string | null, cta_title?: string | null, cta_description?: string | null, cta_button_label?: string | null, features?: Array<{ __typename: 'HomepageFeatures', title?: string | null, description?: any | null, icon_key?: string | null, border_color?: string | null } | null> | null, reviews?: Array<{ __typename: 'HomepageReviews', avatar?: string | null, name?: string | null, rating?: number | null, text?: any | null, platform?: string | null } | null> | null, faqs?: Array<{ __typename: 'HomepageFaqs', question?: string | null, answer?: any | null } | null> | null };

export type ServicePartsFragment = { __typename: 'Service', title: string, description?: string | null, image?: string | null, cta_label?: string | null };

export type About_PagePartsFragment = { __typename: 'About_page', hero_title_prefix?: string | null, hero_title_brand?: string | null, hero_title_suffix?: string | null, hero_button_label?: string | null, about_title?: string | null, about_text?: any | null, about_image?: string | null, vision_title?: string | null, vision_text?: string | null, vision_image?: string | null, mission_title?: string | null, mission_text?: string | null, mission_image?: string | null, cabinet_title?: string | null, cabinet_images?: Array<string | null> | null, send_message_title?: string | null, cta_title?: string | null, cta_description?: string | null, cta_button_label?: string | null };

export type Testimonials_PagePartsFragment = { __typename: 'Testimonials_page', hero_title_line_one?: string | null, hero_title_highlight?: string | null, hero_title_line_two?: string | null, hero_title_line_three?: string | null, hero_description?: string | null, hero_button_label?: string | null, hero_image_1?: string | null, hero_image_2?: string | null, hero_image_3?: string | null, before_after_title?: string | null, more_title?: string | null, before_after_pairs?: Array<{ __typename: 'Testimonials_pageBefore_after_pairs', before_image?: string | null, after_image?: string | null, before_alt?: string | null, after_alt?: string | null } | null> | null, more_panels?: Array<{ __typename: 'Testimonials_pageMore_panels', kind?: string | null, src?: string | null, poster?: string | null, alt?: string | null } | null> | null };

export type Global_SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Global_SettingsQuery = { __typename?: 'Query', global_settings: { __typename: 'Global_settings', id: string, logo?: string | null, primary_phone?: string | null, secondary_phone?: string | null, email?: string | null, address?: string | null, footer_services?: Array<string | null> | null, services_page_title?: string | null, footer_text?: string | null, footer_credit?: string | null, cta_button_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navigation_links?: Array<{ __typename: 'Global_settingsNavigation_links', label?: string | null, path?: string | null } | null> | null, social_links?: Array<{ __typename: 'Global_settingsSocial_links', platform?: string | null, url?: string | null } | null> | null } };

export type Global_SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Global_SettingsFilter>;
}>;


export type Global_SettingsConnectionQuery = { __typename?: 'Query', global_settingsConnection: { __typename?: 'Global_settingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Global_settingsConnectionEdges', cursor: string, node?: { __typename: 'Global_settings', id: string, logo?: string | null, primary_phone?: string | null, secondary_phone?: string | null, email?: string | null, address?: string | null, footer_services?: Array<string | null> | null, services_page_title?: string | null, footer_text?: string | null, footer_credit?: string | null, cta_button_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navigation_links?: Array<{ __typename: 'Global_settingsNavigation_links', label?: string | null, path?: string | null } | null> | null, social_links?: Array<{ __typename: 'Global_settingsSocial_links', platform?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, hero_line_one?: string | null, hero_line_one_suffix?: string | null, hero_line_two?: string | null, hero_line_three?: string | null, hero_image_1?: string | null, hero_image_2?: string | null, hero_image_3?: string | null, hero_arrow?: string | null, hero_button_label?: string | null, hero_phone_label?: string | null, about_title?: string | null, about_text?: any | null, about_image?: string | null, features_title?: string | null, services_title?: string | null, reviews_title?: string | null, faq_title?: string | null, cta_title?: string | null, cta_description?: string | null, cta_button_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'HomepageFeatures', title?: string | null, description?: any | null, icon_key?: string | null, border_color?: string | null } | null> | null, reviews?: Array<{ __typename: 'HomepageReviews', avatar?: string | null, name?: string | null, rating?: number | null, text?: any | null, platform?: string | null } | null> | null, faqs?: Array<{ __typename: 'HomepageFaqs', question?: string | null, answer?: any | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, hero_line_one?: string | null, hero_line_one_suffix?: string | null, hero_line_two?: string | null, hero_line_three?: string | null, hero_image_1?: string | null, hero_image_2?: string | null, hero_image_3?: string | null, hero_arrow?: string | null, hero_button_label?: string | null, hero_phone_label?: string | null, about_title?: string | null, about_text?: any | null, about_image?: string | null, features_title?: string | null, services_title?: string | null, reviews_title?: string | null, faq_title?: string | null, cta_title?: string | null, cta_description?: string | null, cta_button_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'HomepageFeatures', title?: string | null, description?: any | null, icon_key?: string | null, border_color?: string | null } | null> | null, reviews?: Array<{ __typename: 'HomepageReviews', avatar?: string | null, name?: string | null, rating?: number | null, text?: any | null, platform?: string | null } | null> | null, faqs?: Array<{ __typename: 'HomepageFaqs', question?: string | null, answer?: any | null } | null> | null } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, title: string, description?: string | null, image?: string | null, cta_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, title: string, description?: string | null, image?: string | null, cta_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type About_PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type About_PageQuery = { __typename?: 'Query', about_page: { __typename: 'About_page', id: string, hero_title_prefix?: string | null, hero_title_brand?: string | null, hero_title_suffix?: string | null, hero_button_label?: string | null, about_title?: string | null, about_text?: any | null, about_image?: string | null, vision_title?: string | null, vision_text?: string | null, vision_image?: string | null, mission_title?: string | null, mission_text?: string | null, mission_image?: string | null, cabinet_title?: string | null, cabinet_images?: Array<string | null> | null, send_message_title?: string | null, cta_title?: string | null, cta_description?: string | null, cta_button_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type About_PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<About_PageFilter>;
}>;


export type About_PageConnectionQuery = { __typename?: 'Query', about_pageConnection: { __typename?: 'About_pageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'About_pageConnectionEdges', cursor: string, node?: { __typename: 'About_page', id: string, hero_title_prefix?: string | null, hero_title_brand?: string | null, hero_title_suffix?: string | null, hero_button_label?: string | null, about_title?: string | null, about_text?: any | null, about_image?: string | null, vision_title?: string | null, vision_text?: string | null, vision_image?: string | null, mission_title?: string | null, mission_text?: string | null, mission_image?: string | null, cabinet_title?: string | null, cabinet_images?: Array<string | null> | null, send_message_title?: string | null, cta_title?: string | null, cta_description?: string | null, cta_button_label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Testimonials_PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Testimonials_PageQuery = { __typename?: 'Query', testimonials_page: { __typename: 'Testimonials_page', id: string, hero_title_line_one?: string | null, hero_title_highlight?: string | null, hero_title_line_two?: string | null, hero_title_line_three?: string | null, hero_description?: string | null, hero_button_label?: string | null, hero_image_1?: string | null, hero_image_2?: string | null, hero_image_3?: string | null, before_after_title?: string | null, more_title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, before_after_pairs?: Array<{ __typename: 'Testimonials_pageBefore_after_pairs', before_image?: string | null, after_image?: string | null, before_alt?: string | null, after_alt?: string | null } | null> | null, more_panels?: Array<{ __typename: 'Testimonials_pageMore_panels', kind?: string | null, src?: string | null, poster?: string | null, alt?: string | null } | null> | null } };

export type Testimonials_PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Testimonials_PageFilter>;
}>;


export type Testimonials_PageConnectionQuery = { __typename?: 'Query', testimonials_pageConnection: { __typename?: 'Testimonials_pageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Testimonials_pageConnectionEdges', cursor: string, node?: { __typename: 'Testimonials_page', id: string, hero_title_line_one?: string | null, hero_title_highlight?: string | null, hero_title_line_two?: string | null, hero_title_line_three?: string | null, hero_description?: string | null, hero_button_label?: string | null, hero_image_1?: string | null, hero_image_2?: string | null, hero_image_3?: string | null, before_after_title?: string | null, more_title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, before_after_pairs?: Array<{ __typename: 'Testimonials_pageBefore_after_pairs', before_image?: string | null, after_image?: string | null, before_alt?: string | null, after_alt?: string | null } | null> | null, more_panels?: Array<{ __typename: 'Testimonials_pageMore_panels', kind?: string | null, src?: string | null, poster?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export const Global_SettingsPartsFragmentDoc = gql`
    fragment Global_settingsParts on Global_settings {
  __typename
  logo
  primary_phone
  secondary_phone
  email
  address
  navigation_links {
    __typename
    label
    path
  }
  social_links {
    __typename
    platform
    url
  }
  footer_services
  services_page_title
  footer_text
  footer_credit
  cta_button_label
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  hero_line_one
  hero_line_one_suffix
  hero_line_two
  hero_line_three
  hero_image_1
  hero_image_2
  hero_image_3
  hero_arrow
  hero_button_label
  hero_phone_label
  about_title
  about_text
  about_image
  features_title
  features {
    __typename
    title
    description
    icon_key
    border_color
  }
  services_title
  reviews_title
  reviews {
    __typename
    avatar
    name
    rating
    text
    platform
  }
  faq_title
  faqs {
    __typename
    question
    answer
  }
  cta_title
  cta_description
  cta_button_label
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  title
  description
  image
  cta_label
}
    `;
export const About_PagePartsFragmentDoc = gql`
    fragment About_pageParts on About_page {
  __typename
  hero_title_prefix
  hero_title_brand
  hero_title_suffix
  hero_button_label
  about_title
  about_text
  about_image
  vision_title
  vision_text
  vision_image
  mission_title
  mission_text
  mission_image
  cabinet_title
  cabinet_images
  send_message_title
  cta_title
  cta_description
  cta_button_label
}
    `;
export const Testimonials_PagePartsFragmentDoc = gql`
    fragment Testimonials_pageParts on Testimonials_page {
  __typename
  hero_title_line_one
  hero_title_highlight
  hero_title_line_two
  hero_title_line_three
  hero_description
  hero_button_label
  hero_image_1
  hero_image_2
  hero_image_3
  before_after_title
  before_after_pairs {
    __typename
    before_image
    after_image
    before_alt
    after_alt
  }
  more_title
  more_panels {
    __typename
    kind
    src
    poster
    alt
  }
}
    `;
export const Global_SettingsDocument = gql`
    query global_settings($relativePath: String!) {
  global_settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Global_settingsParts
  }
}
    ${Global_SettingsPartsFragmentDoc}`;
export const Global_SettingsConnectionDocument = gql`
    query global_settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Global_settingsFilter) {
  global_settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Global_settingsParts
      }
    }
  }
}
    ${Global_SettingsPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const About_PageDocument = gql`
    query about_page($relativePath: String!) {
  about_page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...About_pageParts
  }
}
    ${About_PagePartsFragmentDoc}`;
export const About_PageConnectionDocument = gql`
    query about_pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: About_pageFilter) {
  about_pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...About_pageParts
      }
    }
  }
}
    ${About_PagePartsFragmentDoc}`;
export const Testimonials_PageDocument = gql`
    query testimonials_page($relativePath: String!) {
  testimonials_page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Testimonials_pageParts
  }
}
    ${Testimonials_PagePartsFragmentDoc}`;
export const Testimonials_PageConnectionDocument = gql`
    query testimonials_pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Testimonials_pageFilter) {
  testimonials_pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Testimonials_pageParts
      }
    }
  }
}
    ${Testimonials_PagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      global_settings(variables: Global_SettingsQueryVariables, options?: C): Promise<{data: Global_SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Global_SettingsQueryVariables, query: string}> {
        return requester<{data: Global_SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Global_SettingsQueryVariables, query: string}, Global_SettingsQueryVariables>(Global_SettingsDocument, variables, options);
      },
    global_settingsConnection(variables?: Global_SettingsConnectionQueryVariables, options?: C): Promise<{data: Global_SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Global_SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: Global_SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Global_SettingsConnectionQueryVariables, query: string}, Global_SettingsConnectionQueryVariables>(Global_SettingsConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    about_page(variables: About_PageQueryVariables, options?: C): Promise<{data: About_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageQueryVariables, query: string}> {
        return requester<{data: About_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageQueryVariables, query: string}, About_PageQueryVariables>(About_PageDocument, variables, options);
      },
    about_pageConnection(variables?: About_PageConnectionQueryVariables, options?: C): Promise<{data: About_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageConnectionQueryVariables, query: string}> {
        return requester<{data: About_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageConnectionQueryVariables, query: string}, About_PageConnectionQueryVariables>(About_PageConnectionDocument, variables, options);
      },
    testimonials_page(variables: Testimonials_PageQueryVariables, options?: C): Promise<{data: Testimonials_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Testimonials_PageQueryVariables, query: string}> {
        return requester<{data: Testimonials_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Testimonials_PageQueryVariables, query: string}, Testimonials_PageQueryVariables>(Testimonials_PageDocument, variables, options);
      },
    testimonials_pageConnection(variables?: Testimonials_PageConnectionQueryVariables, options?: C): Promise<{data: Testimonials_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Testimonials_PageConnectionQueryVariables, query: string}> {
        return requester<{data: Testimonials_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Testimonials_PageConnectionQueryVariables, query: string}, Testimonials_PageConnectionQueryVariables>(Testimonials_PageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/f15a2d7f-d408-40f2-a0fb-1b5c57e41c0f/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  