[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://biodental.netlify.app"
  NODE_VERSION = "20"
  # RESEND_API_KEY must be added in the Netlify UI
  # You can add it at Settings > Build & deploy > Environment > Environment variables

# For Next.js projects, we need this plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Set custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 